/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RuleRouteImport } from './routes/rule'
import { Route as EmployeeCardRouteImport } from './routes/employeeCard'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AiPostsRouteImport } from './routes/aiPosts'
import { Route as AiContentRouteImport } from './routes/aiContent'
import { Route as TaskReportRouteImport } from './routes/TaskReport'
import { Route as SaleReportRouteImport } from './routes/SaleReport'
import { Route as IndexRouteImport } from './routes/index'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleRoute = RuleRouteImport.update({
  id: '/rule',
  path: '/rule',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCardRoute = EmployeeCardRouteImport.update({
  id: '/employeeCard',
  path: '/employeeCard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPostsRoute = AiPostsRouteImport.update({
  id: '/aiPosts',
  path: '/aiPosts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiContentRoute = AiContentRouteImport.update({
  id: '/aiContent',
  path: '/aiContent',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskReportRoute = TaskReportRouteImport.update({
  id: '/TaskReport',
  path: '/TaskReport',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleReportRoute = SaleReportRouteImport.update({
  id: '/SaleReport',
  path: '/SaleReport',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SaleReport': typeof SaleReportRoute
  '/TaskReport': typeof TaskReportRoute
  '/aiContent': typeof AiContentRoute
  '/aiPosts': typeof AiPostsRoute
  '/avatar': typeof AvatarRoute
  '/employeeCard': typeof EmployeeCardRoute
  '/rule': typeof RuleRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SaleReport': typeof SaleReportRoute
  '/TaskReport': typeof TaskReportRoute
  '/aiContent': typeof AiContentRoute
  '/aiPosts': typeof AiPostsRoute
  '/avatar': typeof AvatarRoute
  '/employeeCard': typeof EmployeeCardRoute
  '/rule': typeof RuleRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/SaleReport': typeof SaleReportRoute
  '/TaskReport': typeof TaskReportRoute
  '/aiContent': typeof AiContentRoute
  '/aiPosts': typeof AiPostsRoute
  '/avatar': typeof AvatarRoute
  '/employeeCard': typeof EmployeeCardRoute
  '/rule': typeof RuleRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/SaleReport'
    | '/TaskReport'
    | '/aiContent'
    | '/aiPosts'
    | '/avatar'
    | '/employeeCard'
    | '/rule'
    | '/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/SaleReport'
    | '/TaskReport'
    | '/aiContent'
    | '/aiPosts'
    | '/avatar'
    | '/employeeCard'
    | '/rule'
    | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/SaleReport'
    | '/TaskReport'
    | '/aiContent'
    | '/aiPosts'
    | '/avatar'
    | '/employeeCard'
    | '/rule'
    | '/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SaleReportRoute: typeof SaleReportRoute
  TaskReportRoute: typeof TaskReportRoute
  AiContentRoute: typeof AiContentRoute
  AiPostsRoute: typeof AiPostsRoute
  AvatarRoute: typeof AvatarRoute
  EmployeeCardRoute: typeof EmployeeCardRoute
  RuleRoute: typeof RuleRoute
  ScheduleRoute: typeof ScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule': {
      id: '/rule'
      path: '/rule'
      fullPath: '/rule'
      preLoaderRoute: typeof RuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employeeCard': {
      id: '/employeeCard'
      path: '/employeeCard'
      fullPath: '/employeeCard'
      preLoaderRoute: typeof EmployeeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiPosts': {
      id: '/aiPosts'
      path: '/aiPosts'
      fullPath: '/aiPosts'
      preLoaderRoute: typeof AiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiContent': {
      id: '/aiContent'
      path: '/aiContent'
      fullPath: '/aiContent'
      preLoaderRoute: typeof AiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TaskReport': {
      id: '/TaskReport'
      path: '/TaskReport'
      fullPath: '/TaskReport'
      preLoaderRoute: typeof TaskReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SaleReport': {
      id: '/SaleReport'
      path: '/SaleReport'
      fullPath: '/SaleReport'
      preLoaderRoute: typeof SaleReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SaleReportRoute: SaleReportRoute,
  TaskReportRoute: TaskReportRoute,
  AiContentRoute: AiContentRoute,
  AiPostsRoute: AiPostsRoute,
  AvatarRoute: AvatarRoute,
  EmployeeCardRoute: EmployeeCardRoute,
  RuleRoute: RuleRoute,
  ScheduleRoute: ScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
