/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RuleRouteImport } from './routes/rule'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeCardRouteImport } from './routes/employeeCard'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AiContentRouteImport } from './routes/aiContent'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleRoute = RuleRouteImport.update({
  id: '/rule',
  path: '/rule',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCardRoute = EmployeeCardRouteImport.update({
  id: '/employeeCard',
  path: '/employeeCard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiContentRoute = AiContentRouteImport.update({
  id: '/aiContent',
  path: '/aiContent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiContent': typeof AiContentRoute
  '/avatar': typeof AvatarRoute
  '/employeeCard': typeof EmployeeCardRoute
  '/login': typeof LoginRoute
  '/roles': typeof RolesRoute
  '/rule': typeof RuleRoute
  '/schedule': typeof ScheduleRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiContent': typeof AiContentRoute
  '/avatar': typeof AvatarRoute
  '/employeeCard': typeof EmployeeCardRoute
  '/login': typeof LoginRoute
  '/roles': typeof RolesRoute
  '/rule': typeof RuleRoute
  '/schedule': typeof ScheduleRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aiContent': typeof AiContentRoute
  '/avatar': typeof AvatarRoute
  '/employeeCard': typeof EmployeeCardRoute
  '/login': typeof LoginRoute
  '/roles': typeof RolesRoute
  '/rule': typeof RuleRoute
  '/schedule': typeof ScheduleRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiContent'
    | '/avatar'
    | '/employeeCard'
    | '/login'
    | '/roles'
    | '/rule'
    | '/schedule'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiContent'
    | '/avatar'
    | '/employeeCard'
    | '/login'
    | '/roles'
    | '/rule'
    | '/schedule'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/aiContent'
    | '/avatar'
    | '/employeeCard'
    | '/login'
    | '/roles'
    | '/rule'
    | '/schedule'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiContentRoute: typeof AiContentRoute
  AvatarRoute: typeof AvatarRoute
  EmployeeCardRoute: typeof EmployeeCardRoute
  LoginRoute: typeof LoginRoute
  RolesRoute: typeof RolesRoute
  RuleRoute: typeof RuleRoute
  ScheduleRoute: typeof ScheduleRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule': {
      id: '/rule'
      path: '/rule'
      fullPath: '/rule'
      preLoaderRoute: typeof RuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employeeCard': {
      id: '/employeeCard'
      path: '/employeeCard'
      fullPath: '/employeeCard'
      preLoaderRoute: typeof EmployeeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiContent': {
      id: '/aiContent'
      path: '/aiContent'
      fullPath: '/aiContent'
      preLoaderRoute: typeof AiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiContentRoute: AiContentRoute,
  AvatarRoute: AvatarRoute,
  EmployeeCardRoute: EmployeeCardRoute,
  LoginRoute: LoginRoute,
  RolesRoute: RolesRoute,
  RuleRoute: RuleRoute,
  ScheduleRoute: ScheduleRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
